### ISSUE TITLE
Benchmarks use `PyParser_ASTFromStringObject`, which is removed from Python 3.10

### ISSUE THREAD

**Issue by dralley** [RustPython/RustPython#3498]
Benchmarks fail to compile on a system with Python 3.10, in my case, Fedora 35.

```
[dalley@localhost RustPython]$ cargo bench
   Compiling rustpython v0.1.2 (/home/dalley/Devel/rustpython-dev/RustPython)
error[E0425]: cannot find function, tuple struct or tuple variant `PyParser_ASTFromStringObject` in crate `python3_sys`
  --> benches/execution.rs:82:32
   |
82 |         let ret = python3_sys::PyParser_ASTFromStringObject(
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `python3_sys`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `rustpython` due to previous error
```

https://github.com/python/cpython/pull/25001

https://github.com/dgrunwald/rust-cpython/commit/7bcf2d305851b5bd22f20c070e0dd75e71ebd388#diff-3a5720e55119ee77dd2db4a0e191e513099d227760a8c40891a9f78872b46982R91

**Comment by fanninpm** [comment]
`git-blame` suggests @coolreader18

**Comment by InnovativeInventor** [comment]
What is the status on this? The benchmarks are still failing . . .
