### PR TITLE
4982 - Implement tm_gmtoff and tm_zone

### LINKED ISSUE #4982: datetime().astimezone() is broken
It seems that RustPython supports datetime().astimezone() while the implementation of this function is broken and attribute  'tm_gmtoff' is missing. See the following example.

Example.py
```
from datetime import datetime
datetime(3001, 1, 19, 7, 59, 59, 999999).astimezone() 
```

Output on RustPython:
```
Traceback (most recent call last):
  File "/home/xxm/Desktop/RustPython/example.py", line 199, in <module>
    datetime(3001, 1, 19, 7, 59, 59, 999999).astimezone() 
  File "/home/xxm/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/59df92d/pylib/Lib/datetime.py", line 1862, in astimezone
    tz = self._local_timezone()
  File "/home/xxm/.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/59df92d/pylib/Lib/datetime.py", line 1856, in _local_timezone
    gmtoff = localtm.tm_gmtoff
AttributeError: 'struct_time' object has no attribute 'tm_gmtoff'
```

Behavior on CPython: works normally

Environment:
RustPython: v0.2.0 (https://github.com/RustPython/RustPython#59df92d7)
CPython: 3.9.0
Ubuntu 18.04

### PR DESCRIPTION
**Pull request by JazzGlobal**
Fixes #4982 

Implements the missing`tm_gmtoff` and `tm_zone` fields in PyStructTime struct. 

The original issue's code example does not work in python 3.12. I used this instead for testing:

```py
import datetime
sgtTimeDelta = datetime.timedelta(hours=5)
sgtTZObject = datetime.timezone(sgtTimeDelta,
                                name="EST")
print(datetime.datetime(3001, 1, 19, 7, 59, 59, 999999, sgtTZObject).astimezone())
```

### CODE REVIEW

**Comment by miviwi** [comment]
I was about to say you don't have to `use` types to well... just *use* them.

Buf if you're a noob then I'll try to explain:
`use` - in contrast with other languages like C++ or JS - only creates an alias, but doesn't actually import anything; In fact in Rust you don't need to import types from a crate at all to use them!

In other words: if you have to name a type - say to call an associated method like `OnceCell::new()` - then you'd need:
```rust
use std::cell::OnceCell;
```
...somewhere in the file/function

but if you're only *calling* a method that returns a `OnceCell` then no `use` is needed (or if you'd use the full name - `std::cell::OnceCell::new()` - then no `use` is needed also)

**Comment by JazzGlobal** [comment]
> I was about to say you don't have to `use` types to well... just _use_ them.
> 
> Buf if you're a noob then I'll try to explain: `use` - in contrast with other languages like C++ or JS - only creates an alias, but doesn't actually import anything; In fact in Rust you don't need to import types from a crate at all to use them!
> 
> In other words: if you have to name a type - say to call an associated method like `OnceCell::new()` - then you'd need:
> 
> ```rust
> use std::cell::OnceCell;
> ```
> 
> ...somewhere in the file/function
> 
> but if you're only _calling_ a method that returns a `OnceCell` then no `use` is needed (or if you'd use the full name - `std::cell::OnceCell::new()` - then no `use` is needed also)

Thanks for the feedback. I did so _right_ before this comment 👍

**Review by youknowone — COMMENTED** [review]
Thank you for contributing. You will want to run some tests about timezones. Here is a few commands not to wait the full CI run.

```
cargo run extra_tests/snippets/stdlib_datetime.py  # most simple one
cargo run Lib/test/test_time.py  # test `time` module
cargo run Lib/test/test_datetime.py  # test `datetime` module
```

**Comment by miviwi** [comment]
@youknowone if I'm right and there's no way to mark a `PyStructSequence` field/s to not get unpacked I don't think you can solve this issue like the author is suggesting

**Comment by JazzGlobal** [comment]
> cargo run extra_tests/snippets/stdlib_datetime.py

I think you're right. I came to conclusion much slower though through messing around with the failing tests.

**Comment by miviwi** [comment]
@JazzGlobal well... this is going to require major changes (completely restructuring the definition of `PyStructTime`) and unless you're up for that - and if you are then great, but it'll be a though one esp. if you're new to Rust - then I'm closing the PR.

So... are you up for it?

**Comment by JazzGlobal** [comment]
> @JazzGlobal well... this is going to require major changes (completely restructuring the definition of `PyStructTime`) and unless you're up for that - and if you are then great, but it'll be a though one esp. if you're new to Rust - then I'm closing the PR.
> 
> So... are you up for it?

yeah I'll fiddle with this for a while long.

**Comment by youknowone** [comment]
@miviwi what are you doing? you don't close the PR. you can't do that.

**Comment by miviwi** [comment]
@youknowone hold on... not closing anything yet, or now that JazzGlobal has spoken not at all 😅

**Comment by JazzGlobal** [comment]
Community is a bit more moderated since I last contributed lol. I'll look at some of the other Traverse implementations for hints on how I should do it for PyStructTime. Thanks guys!

**Comment by youknowone** [comment]
@JazzGlobal Don't worry about it that much. We can solve things step by step, eventually. Nothing changed from the time you visited before.
I agree PyStructureSequence lacks of the feature. The related part is here. https://github.com/RustPython/RustPython/blob/main/derive-impl/src/pystructseq.rs#L5-L28

**Comment by miviwi** [comment]
@JazzGlobal Personally I would first try just leaving `PyStructTime` as a `PyStructSequence` and addding the new fields as getter methods. Yes it'll be slower, but performance and timezones are sort of "opposites" anyway, so... it's worth a shot. Definitely seems easier than uprooting the whole struct

**Comment by youknowone** [comment]
I am not getting how PyTraverse is related to this problem yet. I'd like to fix pystructseq side first.

@JazzGlobal Are you also interested in proc macro? Then the point will be the start point. Otherwise let me make some changes on PyStructSequence. I don't have a good idea how to change it right now though.

**Comment by miviwi** [comment]
@youknowone not as the code is right now, but making the struct a `Traversable` (instead of a `PyStructSequence`) is the only way I could think up to keep those extra fields and be consistent with the docs (i.e. have the tests pass)

**Comment by youknowone** [comment]
Maybe there is confusion. PyTraverse used only for GC. I hope I can solve it with PyStructSequence.

**Comment by JazzGlobal** [comment]
> I am not getting how PyTraverse is related to this problem yet. I'd like to fix pystructseq side first.
> 
> @JazzGlobal Are you also interested in proc macro? Then the point will be the start point. Otherwise let me make some changes on PyStructSequence. I don't have a good idea how to change it right now though.

If utilizing Traverse is not an option then go for it.

**Comment by youknowone** [comment]
I don't think any PR need to be closed due to blocking issues. We always encounter unexpected blocking issues for numerous patches.  We can fix them and come back to the original issue whenever we can. We can review unresolved opened PRs later. But not about unresolved closed PRs. So unclosed PRs are more helpful than closed PRs.

**Comment by youknowone** [comment]
How about adding `#[pystruct(skip)]` to mark fields to ignore?

**Comment by JazzGlobal** [comment]
> How about adding `#[pystruct(skip)]` to mark fields to ignore?

Do you mean `#[pytraverse(skip)]` ?

**Comment by youknowone** [comment]
Yes, adding a new attribute `#[pystruct(<something>)]` 

pytraverse is only used for GC, so not here.

**Comment by JazzGlobal** [comment]
> Yes, adding a new attribute `#[pystruct(<something>)]`
> 
> pytraverse is only used for GC, so not here.

I'm not familiar with Rust macros. Will pystruct("skip") essentially be the same thing implementation-wise as pytraverse?

**Comment by youknowone** [comment]
Unfortunately, it now runs but still tm_gmtoff is not accessible.

**Review by youknowone — APPROVED** [review]
@JazzGlobal It look long time, but finally added required support. Thank you for contributing. I am sorry if you felt inconvenience. Please don't worry to be moderated not by CoC but by code. Whenever everybody every code will be welcomed.

**Comment by JazzGlobal** [comment]
> @JazzGlobal It look long time, but finally added required support. Thank you for contributing. I am sorry if you felt inconvenience. Please don't worry to be moderated not by CoC but by code. Whenever everybody every code will be welcomed.

No problem at all. I like contributing to the project and it isn't about me. Thanks for your help in facilitating this!
